Repository pantographe/view_component-form, pull requests merged in 2021-09, with the labels that each got.

#38 Add block specs for LabelComponent
  .gitignore
  .rubocop.yml
  app/components/view_component/form/base_component.rb
  app/components/view_component/form/field_component.rb
  app/components/view_component/form/label_component.rb
  lib/view_component/form/builder.rb
  spec/view_component/form/label_component_spec.rb
Labels: bug

#53 Bump view_component to 2.40.0
  Gemfile.lock
Labels: dependencies

#54 Per component Builder customization
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  README.md
  lib/generators/vcf/builder/templates/builder.rb.erb
  lib/view_component/form/builder.rb
  spec/internal/app/components/form/label_component.rb
  spec/internal/app/components/form/text_field_component.rb
  spec/internal/app/components/inline_form/label_component.rb
  spec/internal/app/forms/custom_form_builder.rb
  spec/internal/app/forms/inline_custom_form_builder.rb
  spec/view_component/form/builder_spec.rb
Labels: enhancement

#65 Add rspec-html-matchers
  Gemfile
  Gemfile.lock
  gemfiles/rails_6.0.x.gemfile
  gemfiles/rails_6.1.x.gemfile
  gemfiles/rails_head.gemfile
  spec/spec_helper.rb
  spec/support/matchers/eq_html.rb
  spec/view_component/form/date_select_component_spec.rb
  spec/view_component/form/datetime_select_component_spec.rb
  spec/view_component/form/rich_text_area_component_spec.rb
  spec/view_component/form/time_select_component_spec.rb
  spec/view_component/form/time_zone_select_component_spec.rb
Labels: enhancement

#71 Fix Base and Field component errors methods
  .rubocop.yml
  CHANGELOG.md
  app/components/view_component/form/field_component.rb
  bin/rspec
  spec/spec_helper.rb
  spec/view_component/form/base_component_spec.rb
  spec/view_component/form/field_component_spec.rb
Labels: bug
