Repository pantographe/view_component-form, pull requests merged in 2022-02, with the labels that each got.

#106 Add README section about supported helpers
  README.md
Labels: documentation

#104 Backport #field_id from Rails 7
  CHANGELOG.md
  README.md
  lib/view_component/form/builder.rb
  spec/view_component/form/builder_spec.rb
Labels: enhancement

#105 Add ViewComponent::Form::WeekdaySelectComponent
  CHANGELOG.md
  README.md
  app/components/view_component/form/weekday_select_component.rb
  spec/view_component/form/weekday_select_component_spec.rb
Labels: enhancement

#103 Add #label_text helper to FieldComponent
  CHANGELOG.md
  README.md
  app/components/view_component/form/field_component.rb
  spec/support/shared_context/with_translations.rb
  spec/view_component/form/field_component_spec.rb
Labels: enhancement

#107 Setup zeitwerk
  .rubocop.yml
  Gemfile.lock
  app/components/view_component/form/base_component.rb
  lib/view_component/form.rb
  lib/view_component/form/builder.rb
  lib/view_component/form/engine.rb
  view_component-form.gemspec
Labels: enhancement, dependencies

#108 doc: add documentation for tests
  README.md
Labels: documentation

#101 Access validators form a Field component
  CHANGELOG.md
  README.md
  app/components/view_component/form/field_component.rb
  lib/view_component/form/builder.rb
  spec/view_component/form/builder_spec.rb
  spec/view_component/form/field_component_spec.rb
Labels: enhancement
